### PR TITLE
12.0 [2125][FIX] update .travis.yml 

### PR DESCRIPTION
**Pull request by tack-yabeQuartile**
[#2125](https://www.quartile.co/web#id=2125&action=771&model=project.task&view_type=form&menu_id=505)

st1
#45

### CODE REVIEW

**Comment by yostashiro** [comment]
@tack-yabeQuartile This should be done together with the addition of the password security module.

**Comment by tack-yabeQuartile** [comment]
> @tack-yabeQuartile This should be done together with the addition of the password security module.

OK, I agree. (If we merged this before apply password_security, an excess error would be called, I understand.)

**Comment by yostashiro** [comment]
@tack-yabeQuartile You should actually close this PR.  The change on .travis.yml should be in the same PR as the password security module.

**Comment by tack-yabeQuartile** [comment]
> in the same PR

I see, then I close this PR.

**Pull request closed without merging**
